import {DocumentType, ModelOptions,prop} from "@typegoose/typegoose";


//delete the default field that mongoDB autogenerated.
@ModelOptions({
    schemaOptions : {
        toJSON: {
            transform: (doc: DocumentType<ManagerRequest>, ret) => {
                delete ret.__v;
                delete ret._id;
            }
        }
    }
})

//manage request schema

export class ManagerRequest
{
        @prop({required:true,index:true,unique:true,})
        requestId:number;

        
        @prop({required:true})
        employeeId:number;

        @prop({required:true})
        fromManagerId:number;

        @prop({required:true})
        toManagerId:number;

        //I think we don't need to enforce client send the status
        //we can set it when the request created in the service
        @prop({required:false})
        status:string;

        @prop({required:false})
        createdDate:Date;

        //this is updated time shouldnt enforce to fill in
        @prop({required:false})
        updatedDate:Date;


        
}