version: '3'
services:

  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo
    expose:
    - 27017
    ports:
      - 27011:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo2:
    hostname: mongo2
    container_name: localmongo2
    image: mongo
    expose:
    - 27017
    ports:
    - 27012:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo3:
    hostname: mongo3
    container_name: localmongo3
    image: mongo
    expose:
    - 27017
    ports:
    - 27013:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  # database:
  #   image: mongo
  #   # container_name: 'blah'
  #   # volumes:
  #   #   - "./database/dbinfo:/data/db"
  #   ports:
  #     - "27017:27017"

  # mongo-seed:
  #   image: mongo
  #   network_mode: service:database
  #   command: mongoimport --host database --db testd --collection testc --type json --file /data/db/init.json --jsonArray
  #   volumes:
  #     - "./database/dbinfo:/data/db"

  # backend:
  #   build: backend
  #   command: /bin/bash -c "npm rebuild bcrypt --build-from-source && npm start"
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./backend:/usr/src/app:rw
  #     - /usr/src/app/node_modules

  # frontend:
  #   build: frontend
  #   command: npm start
  #   depends_on:
  #     - backend
  #   ports:
  #     - 4200:4200
  #   volumes:
  #     - ./frontend:/usr/src/app:rw
  #     - /usr/src/app/node_modules