version: '3'
services:

  backend:
    build: backend
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/src/app:rw
      - /usr/src/app/node_modules

  frontend:
    build: frontend
    command: npm start
    depends_on:
      - backend
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/usr/src/app:rw
      - /usr/src/app/node_modules
